### ISSUE TITLE
Documenter les variables manquantes ou remplacer par les variables utilisées

### ISSUE THREAD

**Issue by mquandalle** [betagouv/publicodes#103]
cf. #74

**Comment by laem** [comment]
Je profite de cette PR pour commencer à documenter un peu les missingVariables. Je pense qu'une page sur publi.codes qui explique comment on les utilise pour construire des formulaires automatiquement serait essentielle, pour compléter le petit paragraphe https://publi.codes/documentation/se-lancer#variables-manquantes. 

Les missing variables renvoyées par publicodes sont associées à l'évaluation d'une règle. Elles sont triables par un indice d'importance dans la perspective du calcul d'une règle. 

En gros, dès qu'une variable est rencontrée lors d'un calcul, son indice est incrémenté dans le tableau des missing variables. Avec une subtilité : dans un mécanisme comme les `variations`, on a des couples `condition: conséquence`. On sait donc que les variables présentes dans l’expression `condition` sont plus importantes en termes d'ordre que celles des conséquences, car la valeur de la condition va potentiellement rendre inutile la conséquence, l'inverse n'étant pas vraie. 

De la même façon, lors d'un `applicable si: x; formule: y`, on sait que x conditionne l'évaluation de y. 

Le code des mécanismes donne donc un `bonus` aux variables conditionnelles.  

Ce mécanisme nous permet donc de construire empiriquement un ordre pour les questions, et donc un formulaire qui a un minimum de sens pour l'utilisateur. Dans bien des cas, cet ordre est tout aussi bon que s'il avait été choisi par le développeur. 

Illustration. 

```yaml

a:
    formule:
      variations:
        - si: type = 'buche'
          alors: consommation . buche * facteur . buche
        - sinon: consommation . granulés * facteur . granulés
  
  type:
    par défaut: "'buche'"
    formule:
      une possibilité:
        choix obligatoire: oui
        possibilités:
          - buche
          - granulés
  
  type . buche:
  type . granulés:
  
  consommation: oui
  
  consommation . buche:
    formule: combien * 10
  consommation . buche . combien:
    question: Alors ?
  
  
  consommation . granulés:·
    question: Euh ?·
  
  facteur: oui
  facteur . granulés: 18
  facteur . buche: 30

```

Cet bout de code va générer 3 questions : le choix bois/granulé, la consommation bois, la consommation granulé. Sauf qu'évidemment, on veut que la question du choix soit posée avant la question des consommations, car l'une sera complètement inintéressante pour l'utilisateur. 

Dans cette version du code, ça ne marche pas. Car l'algorithme d'évaluation, pour une raison ou pour une autre (et je crois que c'est justement à cause de l'évaluation de l'applicabilité du parent, #74), donne un indice plus important à la question de consommation qui n'est pas active (car le type a une valeur par défaut). 

```js
{ type: 1.0002, 'consommation . buche . combien': 2.0000999999999998 }
```

Voilà une façon de réorganiser le code pour que cet ordre des questions soit respecté. Ce n'est pas une science exacte, les deux choix peuvent se défendre. 

```yaml
 a:
    formule:
      variations: 
        - si: type = 'buche'
          alors: type . buche . consommation * facteur . buche
        - sinon: type . granulés . consommation * facteur . granulés
  
  type:
    par défaut: "'buche'"
    formule:   
      une possibilité:
        choix obligatoire: oui
        possibilités:
          - buche                                                                                        
          - granulés                                                                                     
                                                                                                         
  type . buche:                                                                                          
  type . granulés:                                                                                       
                                                                                                         
                                                                                                         
  type . buche . consommation:                                                                           
    formule: combien * 10                                                                                
  type . buche . consommation . combien:                                                                 
    question: Alors ?                                                                                    
                                                                                                         
                                                                                                         
  type . granulés . consommation:·                                                                       
    question: Euh ?·                                                                                     
                                                                                                         
  facteur: oui                                                                                           
  facteur . granulés: 18                                                                                 
  facteur . buche: 30

```

Dans d'autres cas, l'ordre automatique, largement imparfait, ne suffit pas. L'avantage, c'est que rien ne nous oblige à l'utiliser, et l'équipe mon-entreprise comme nosgestesclimat va donc personnaliser cet ordre dans ces fonctions [getNextQuestions](https://github.com/betagouv/mon-entreprise/blob/master/mon-entreprise/source/components/utils/useNextQuestion.tsx#L82). Dans un autre projet, Mon Match carbone (fork de NGC), le développeur prend la main sur l'ordre des questions [ici](https://github.com/pascalbes/monmatchcarbone-site/blob/389c1c2505872fc19534853e94e7d12cf295ddf3/source/components/conversation/Conversation.tsx#L57).
