### ISSUE TITLE
[mécanisme texte] Retourner "non définie" si une des variables est non définie

### ISSUE THREAD

**Issue by johangirod** [betagouv/publicodes#172]
### Actuel
```yaml
LFR1: "'N'"
code:
  texte: '{{ secteur }};{{ LFSS }};{{ LFR1 }}'
```
Si toutes les valeurs sont indéfinies, cette formule évalue à  `Pas encore défini;Pas encore défini;N`
On aimerait que le comportement vis-à-vis des valeurs non définies soit le même que pour les autres mécanismes : qu'elles se propagent par contamination. En l'occurrence, que `code` soit également "pas encore définie".

Il est assez simple de le mettre en œuvre.
