### ISSUE TITLE
Calcul du plafond de la sécurité sociale erroné

### ISSUE THREAD

**Issue by fmata** [betagouv/publicodes#177]
Bonjour,

Le calcul du plafond de la sécurité sociale qui est fait dans la règle `contrat salarié . plafond sécurité sociale` nous semble faux depuis 2017 où les URSSAF demandent à ce que les absences non rémunérées soient prises en compte en jours calendaires au lieu d'être en heures.

> valeur mensuelle du plafond x (nombre de jours rémunérés de la période d'emploi / nombre de jours calendaires du mois)

cf https://www.urssaf.fr/portail/home/employeur/calculer-les-cotisations/la-base-de-calcul/lassiette-maximale/la-notion-de-plafond/le-calcul-du-plafond/prise-en-compte-des-absences.html

Ce qui donnerait quelque chose comme : 

Avant :
```yaml
contrat salarié . temps de travail . quotité de travail effective:
  description: >-
    Le plafond de la sécurité sociale doit être pro-ratisé en retirant les
    absences ainsi que les jours passés au chômage partiel.
  formule: temps de travail . temps effectif / (base légale * période . semaines par mois)

contrat salarié . plafond sécurité sociale:
  acronyme: PSS
  unité: €/mois
  formule:
    valeur: plafond sécurité sociale temps plein * temps de travail . quotité de travail effective
    plancher: 1 €/mois
```
Après (pseudo code) :
```yaml
contrat salarié . temps de travail . quotité de travail effective:
  formule: arrondi_entier_supérieur(contrat salarié . temps de travail . base légale / 5) / période . jours calendaires par mois

contrat salarié . plafond sécurité sociale:
  acronyme: PSS
  unité: €/mois
  formule:
    valeur: plafond sécurité sociale temps plein * temps de travail . quotité de travail effective
    plancher: 1 €/mois
```
Que pensez-vous de ce changement ? Et de son implémentation ? A ma connaissance il manquerait aujourd'hui la possibilité de faire un arrondi à l'unité supérieure.
