### ISSUE TITLE
Pouvoir utiliser le mécanisme `somme` pour concaténer les textes

### ISSUE THREAD

**Issue by johangirod** [betagouv/publicodes#186]
J'ai le cas d'usage suivant : 
```yaml
  somme:
    - variations:
        - si: entreprise . catégorie juridique . EI
          alors:
            texte: |-
              Par défaut les entreprises individuelles sont imposées à l'impôt sur le revenu. Cependant, 
              votre entreprise peut être imposée à l'**impôt sur les société** si : 
              - c'est une **entreprise individuelle à responsabilité limitée** (EIRL),
              - et **une demande a été envoyée aux impôts** pour choisir l'impôt sur les sociétés.

              Ce choix a pu être fait pour vous permettre de vous verser des dividendes par exemple.
        - si: entreprise . catégorie juridique . SARL . unipersonnelle
          alors:
            texte: |-
              Votre entreprise est imposée à l'impôt sur les sociétés (IS) si une demande a été envoyée aux impôts
              pour choisir l'impôt sur les sociétés (IS). Cette demande a pu avoir lieu lors de la création ou après.

              Il est assez fréquent que les EURL choisissent l'option de l'impôt sur les sociétés. Ce choix permet 
              de se verser des dividendes par exemple.
    - texte: |-
  
        En cas de doutes, **demandez à votre comptable**.
```

Cela marche, sauf que la chaîne de carcatère retournée est préfixée par `0`. Cela vient de l'implémentation de `somme` qui fait un `reduce` à partir de l'élément neutre (0). 

J'aimerai bien pouvoir concaténer des textes sans avoir à passer par le mécanisme `texte` et la définition de variables intermédiaires. Peut-être un nouveau mécanisme ?

A continuer de réfléchir (non urgent)
