### ISSUE TITLE
Cycle parent-enfant

### ISSUE THREAD

**Issue by mquandalle** [betagouv/publicodes#200]
Dans l'exemple suivant on a un cycle lors de l'évaluation. Le test fonctionne uniquement grâce au garde-fou qui après 15 itérations considère que le parent est `undefined` et donc qu'il n'y a pas de désactivation de branche.

```yaml
dieu le père:
  valeur:
    nom: jésus
    valeur: oui
  exemples:
    - valeur attendue: true
```

[studio](https://publi.codes/studio/?code=dieu+le+p%C3%A8re%3A%0A++valeur%3A%0A++++nom%3A+j%C3%A9sus%0A++++valeur%3A+oui%0A++exemples%3A%0A++++-+valeur+attendue%3A+true)

Ici la règle `jesus` est le fils de `dieu le père` mais on a aussi `dieu le père = jésus`. Vu que jésus est une règle booléenne c'est aussi le cas de dieu le père, et donc dieu le père est le “nullableParent” de jésus.

Cela provoque un cycle à l'évaluation pour déterminer l'applicabilité du parent.

(Oui l'exemple est très inspiré 😄)
