### ISSUE TITLE
Un parent non applicable ne devrait pas désactiver les enfants lorsqu'il les évalue dans son contexte

### ISSUE THREAD

**Issue by johangirod** [betagouv/publicodes#206]
Un problème est apparu sur mon-entreprise suite à la réécriture des règles pour la dernière version de publicodes qui change la désactivation de branche https://github.com/betagouv/mon-entreprise/issues/2084

```yaml
contrat salarié . frais professionnels . titres-restaurant:
  applicable si:
    nom: éligible
    question: Le salarié reçoit-il des titres-restaurant ?
    par défaut: non
```

La question de l'égibilité ne sera jamais posée car par défaut valant "non"... ce qui la rend `non applicable`.

[Voir le studio](https://publi.codes/studio?code=titre-restau%3A%0A++applicable+si%3A%0A++++nom%3A+%C3%A9ligible%0A++++question%3A+Le+salari%C3%A9+re%C3%A7oit-il+des+titres-restaurant+%3F%0A++++par+d%C3%A9faut%3A+non%0A++formule%3A+4%E2%82%AC)

On avait évoqué l'idée que la non applicabilité des parents soit l'équivalent d'un `rend non applicable` de toutes les références vers les enfants depuis l'extérieur de l'espace de nom. Mais quand ces références sont utilisée depuis l'espace de nom `non applicable` elles ne soient pas remplacée. 

Ce n'est pas bloquant : il suffit de déplacer la règle de l'applicabilité dans un espace de nom frère :
```yaml
contrat salarié . frais professionnels . titres-restaurant:
    question: Le salarié reçoit-il des titres-restaurant ?
    par défaut: non

contrat salarié . frais professionnels . titres-restaurant . montant:
  ..
```

En revanche ça peut poser problème dans le cas ou la condition d'applicabilité fait appel à des règles enfants : 
```yaml
ma règle: 
  applicable si: montant < plafond
  valeur: 
    nom: montant
    ...
```

Ou encore pour l'évaluation de texte dans le contexte de la règle : 

```yaml
ma règle:
   description: 
     texte: |
       Le plafond maximum est de {{ plafond }} ce qui donne le droit à une aide d'un montant de {{ montant }}

ma règle . plafond:
ma règle . montant:
```
Lorsque la `ma règle` est `non applicable`, la description sera : 
 ```
       Le plafond maximum est de Non applicable ce qui donne le droit à une aide d'un montant de Non applicable
```

**Comment by mquandalle** [comment]
Merci pour les exemples, j'ai essayé d'intégrer un correctif dans #203 qui concerne aussi la désactivation de branche et l'applicabilité parent-enfant, mais je suis un peu embrouillé.

Si je comprends bien il faudrait qu'on est simultanément les 2 comportements suivants :

```yaml
espace 1: non           # nodeValue = false
espace 1 . enfant: non  # nodeValue = null (désactivé par le parent)

espace 2: enfant        # nodeValue = false
espace 2 . enfant: non  # nodeValue = false
```

**Comment by laem** [comment]
[Exemple qui m'a piégé](https://publi.codes/studio/revenu#aide%20.%20condition%3A%20revenu%20%3D%20'sup%C3%A9rieur'%0Aaide%20.%20condition%202%3A%20revenu%20%3D%20'sup%C3%A9rieur'%0Atest%20condition%3A%20aide%20.%20condition%20%3D%20oui%0Atest%20condition%202%3A%20aide%20.%20condition%202%20%3D%20oui%0A%0Aaide%20.%20montant%3A%20%0A%20%20non%20applicable%20si%3A%20aide%20.%20condition%0A%20%20valeur%3A%2012%0Aaide%3A%20%0A%20%20valeur%3A%20montant%0A%0Arevenu%3A%20%22'sup%C3%A9rieur'%22)


```yaml 

aide . condition: revenu = 'supérieur'
aide . condition 2: revenu = 'supérieur'
test condition: aide . condition = oui
test condition 2: aide . condition 2 = oui

aide . montant: 
  non applicable si: aide . condition
  valeur: 12
aide: 
  valeur: montant

revenu: "'supérieur'"

```
