### ISSUE TITLE
Erreur fatale dans le studio avec le rend non applicable

### ISSUE THREAD

**Issue by mquandalle** [betagouv/publicodes#245]
```yaml
nouveau salarié:
  valeur: oui
  rend non applicable: prime de vacances

prime de vacances: 200€
```

> TypeError
> r is undefined

[studio](https://publi.codes/studio/aides/montant-total?code=nouveau+salari%C3%A9%3A%0A++valeur%3A+oui%0A++rend+non+applicable%3A+prime+de+vacances%0A%0Aprime+de+vacances%3A+200%E2%82%AC)
