### ISSUE TITLE
Bug sur le type d'une somme si une valeur est non applicable

### ISSUE THREAD

**Issue by johangirod** [betagouv/publicodes#251]
```yaml
somme: 
  somme:
    - applicable si: non
      valeur: 5 coucou
    - 4
```
https://publi.codes/studio/somme?code=somme%3A+%0A++somme%3A%0A++++-+applicable+si%3A+non%0A++++++valeur%3A+5+couco%0A++++-+4

On s'attend à ce que l'unité de `somme` soit `coucou`. Hors la somme est marquée comme sans unité.
