### ISSUE TITLE
Chaîne de caractères mal formée

### ISSUE THREAD

**Issue by mquandalle** [betagouv/publicodes#380]
Dans la règle suivante :

```yaml
aide vallée d'ossau:
  applicable si: epci = 'CC de la Vallée d'Ossau'
  valeur: 100€
```

on s'attend à avoir une erreur de syntaxe car dans la ligne `applicable si` le guillemet de “Vallée d'Ossau” termine prématurément la chaîne de caractère.

Mais par quelque étrange magie sombre publicodes parse cette chaîne comme si de rien n'était. cf. [studio](https://publi.codes/studio/aide-vall%C3%A9e-d'ossau#aide%20vall%C3%A9e%20d'ossau%3A%0A%20%20applicable%20si%3A%20epci%20%3D%20'CC%20de%20la%20Vall%C3%A9e%20d'Ossau'%0A%20%20valeur%3A%20100%E2%82%AC%0A%0Aepci%3A%20%22''%22%0A)
