### ISSUE TITLE
Documentation : valeur du "applicable si" contaminée par la valeur de la règle

### ISSUE THREAD

**Issue by mquandalle** [betagouv/publicodes#383]
Dans la documentation, un `applicable si` actif prend la valeur de la règle

```yaml
prix:
  applicable si: oui # affiche 3€ dans la doc
  valeur: 3 €
```

[studio](https://publi.codes/studio/prix#prix%3A%0A%20%20applicable%20si%3A%20oui%0A%20%20valeur%3A%20'%22pourquoi%20cette%20valeur%20vient%20dans%20le%20applicable%20si%22')

![image](https://github.com/betagouv/publicodes/assets/1730702/38baa314-cb6e-48a4-8183-2fab1a7aa46f)
