### ISSUE TITLE
Définir les suggestions comme une liste de règles

### ISSUE THREAD

**Issue by mquandalle** [betagouv/publicodes#79]
Actuellement les suggestions de réponses sont définies à partir d'un dictionnaire clé/valeur où la clé est le label de la suggestion et la valeur est l'expression publicodes à mettre dans la situation :

```yaml
contrat salarié . rémunération . brut de base:
  suggestions:
    salaire médian: 2300 €/mois
    SMIC: SMIC temps plein
```

![image](https://user-images.githubusercontent.com/1730702/125304444-e3cf9e00-e32d-11eb-9906-dc17ea862732.png)

Depuis que l'on peut définir des règles “inline” il serait plus aligné avec le reste du langage de définir les suggestions comme une liste de règles.

```yaml
contrat salarié . rémunération . brut de base:
  suggestions:
    - nom: salaire médian
      valeur: 2300 €/mois
    - SMIC temps plein
```

Si on référence une règle on peut directement utiliser son nom court, plutôt que le définir en double comme pour `SMIC: SMIC`. si on référence une valeur comme `2300 €/an`, l'écriture `nom: salarie médian` est plus alignée avec ce qui est utilisé dans d'autres parties du langage.

Enfin ce modèle permet de s'intégrer avec les autres fonctionnalités du langage comme l'applicabilité, on pourrait ainsi proposer une option `gratification minimale` qui s'afficherait seulement pour un stage :

```yaml
contrat salarié . rémunération . brut de base:
  suggestions:
    - nom: salaire médian
      non applicable si: stage
      valeur: 2300 €/mois
    - SMIC temps plein

    # ne s'affiche que pour un stage grâce à la désactivation de l'espace de nom `stage`
    - stage . gratification minimale  
```

Connexe : betagouv/mon-entreprise#451
