### ISSUE TITLE
[SUGGESTION] Mise en place d'héritage

### ISSUE THREAD

**Issue by maxgfr** [betagouv/publicodes#81]
# Problème

Bonjour à tous,
Cette issue, fait plus rôle de suggestion / d'idée concernant la mise en place d'un pattern d'héritage. Le problème que je rencontre, est que je suis souvent confronté à réécrire des références, comme le montre l'exemple ci-dessous :

```yaml
namespace: 
  valeur: 0
  références:
    REF_Z: xxx

namespace . catégorie a:
  valeur: oui

namespace . catégorie a . règle 1 :
  valeur: 1
  références:
    REF_A: xxx
    REF_Z: xxx

namespace . catégorie a . règle 2:
  valeur: 2
  références:
    REF_A: xxx
    REF_B: xxx
    REF_Z: xxx

namespace . catégorie b :
  valeur: oui

namespace . catégorie b . règle 1:
  valeur: 3
  références:
    REF_A: xxx
    REF_Z: xxx

namespace . catégorie b . règle 2:
  valeur: 4
  références:
    REF_A: xxx
    REF_B: xxx
    REF_Z: xxx
```

# Suggestion

Le but serait de gagner du temps en factorisant à l'élément mère des valeurs de références, et de mettre en place un système d'héritage basé sur une key.

```yaml
namespace: 
  valeur: 0
  références:
    REF_Z: xxx
    REF_A: xxx

namespace . catégorie a:
  valeur: oui
  hérite: 
     - namespace: namespace
     - propriété: références

namespace . catégorie a . règle 1 :
  valeur: 1

namespace . catégorie a . règle 2:
  valeur: 2
  références:
    REF_B: xxx

namespace . catégorie b :
  valeur: oui
  hérite: 
     - namespace: namespace
     - propriété: références

namespace . catégorie b . règle 1:
  valeur: 3

namespace . catégorie b . règle 2:
  valeur: 4
  références:
    REF_B: xxx
```

Qu'en pensez-vous ?

Au passage, encore merci pour le développement de cette librairie qui nous fait gagner énormément de temps à la rédaction d'éléments juridiques. 🙏
