### ISSUE TITLE
Changer le fonctionnement du renommage automatique des règles imbriquées

### ISSUE THREAD

**Issue by johangirod** [betagouv/publicodes#83]
### Existant 

Lors de la définition d'une règle imbriquée, un titre est automatiquement affecté à cette dernière, qui prend la forme ```<nom parent> (<nom enfant>).

Ainsi, dans l'exemple suivant : 
```yaml
cotisations . chômage : 
  somme: 
    - nom: salarié
      valeur: 10% * assiette
    - nom: employeur
      valeur: 15% * assiette
```

La règle `cotisations . chômage . salarié` apparaîtra avec le titre `chômage (salarié)`. 
Ce comportement a été choisi pour éviter d'avoir des ambiguités lors de l'utilisation d'un même nom pour les variables imbriquées dans des règles différentes. Ainsi, la somme : 

```yaml
cotisations salariales:
  somme: 
    - chômage . salarié
    - viellesse . salarié
    - ...
 ```
 Apparaîtra avec les variables renommées en `chômage (salarié)` `vieillesse (salarié)` au lieu de `salarié` et `salarié`

### Limites 

Le problème c'est que cette solution est partielle et problématique. En effet, si on veut éviter la verbosité du renommage, il faut explicitement ajouter un titre avec le nom originel de la règle. Cela donne : 

```
courses: 
  somme: 
    - nom: artichaud
      valeur: 2€
      titre: artichaud
    - nom: pâtes
      valeur: 1.2€
      titre: pâtes
    - nom: jus de pomme
      titre: jus de pomme
      valeur: 2.2€
```

Ce qui est assez lourd. 

> Note : ce n'est pas forcément un idiome très courant aujourd'hui, mais il le deviendra avec la possibilité de définir des listes #26 et des objets #14.

Mais le plus dérangeant, c'est que cela ne règle pas fondamentalement le problème de l’ambiguïté des variables nommées affichées dans une liste, qui arrive dès que deux variables dans des espaces de noms différents ont le même titre.

### Proposition d'amélioration

Au lieu de générer un titre automatiquement pour les règles imbriquées (ce qui peut être contraire à la volonté de l'utilisateur), je propose de lever systématiquement l’ambiguïté des règles dans une page de documentation.

Ainsi, lorsque deux règles dans une sommes ont le même titre, on affiche également le titre de leur parent pour les différencier.
